### ISSUE TITLE
Issues on Windows 8

### ISSUE THREAD

**Issue by unexpector** [cjroth/phantomjs-continuous-streaming#1]
I get the following issue when running this on my Windows machine

C:\Users\Steve\vrbrowser\app.js:3
let app = express()
    ^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! phantomjs-streamer@1.0.0 start: `node app.js`
npm ERR! Exit status 1

Any help much appreciated!

**Comment by cjroth** [comment]
Looks like you need to upgrade to the latest Node version.
